:report_in_company_bp:
  :resource: 'report_in_company_bp'
  :description: 'allow access to bp report'
  :params:
    :id: 123
    :bp_id: 'abc123'
    :report_id: 128
  :participant:
    :id: 123
  :methods: ['GET', 'PUT']
  :action: 'allow'
:fake:
  :resource: 'fake'
  :description: 'allow access to bp report'
  :params:
    :id: 3
    :bp_id: 'abc123'
    :report_id: 3
  :participant:
    :id: 3
  :methods: ['GET', 'PUT']
  :action: 'deny'
:account_workspaces_members:
  :resource: 'account_workspaces_members'
  :description: 'allow access to workspaces members'
  :params:
    ':workspace_id': '12'
    ':id': 'admin'
  :participant:
    :id: 123
  :methods: ['GET', 'PUT']
  :action: 'allow'
:not_allowed_path:
  :resource: 'not_allowed'
  :description: 'allow access to bp report'
  :params:
    :id: 123
    :bp_id: 'abc123'
    :report_id: 128
  :participant:
    :id: 123
  :methods: ['GET', 'PUT']
  :action: 'deny'